# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passwords.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='passwords.proto',
  package='passwords',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fpasswords.proto\x12\tpasswords\"1\n\rPasswordQuery\x12\x10\n\x08password\x18\x01 \x03(\t\x12\x0e\n\x06hashes\x18\x02 \x03(\t')
)




_PASSWORDQUERY = _descriptor.Descriptor(
  name='PasswordQuery',
  full_name='passwords.PasswordQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='passwords.PasswordQuery.password', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hashes', full_name='passwords.PasswordQuery.hashes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['PasswordQuery'] = _PASSWORDQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PasswordQuery = _reflection.GeneratedProtocolMessageType('PasswordQuery', (_message.Message,), dict(
  DESCRIPTOR = _PASSWORDQUERY,
  __module__ = 'passwords_pb2'
  # @@protoc_insertion_point(class_scope:passwords.PasswordQuery)
  ))
_sym_db.RegisterMessage(PasswordQuery)


# @@protoc_insertion_point(module_scope)
